# Generated by Django 3.2.6 on 2021-09-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='text',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='result',
            name='evaluation',
            field=models.IntegerField(blank=True),
        ),
    ]
