# Generated by Django 3.2.6 on 2021-09-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210906_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='subTime',
            field=models.CharField(blank=True, choices=[('late', 'Late Submission'), ('onTime', 'Okay')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
